#pragma once

//-----DEBUG-----

//#undef DOH_DEBUG_MEM_USE_CRT
//#define DOH_DEBUG_MEM_USE_CRT
//#undef DOH_DEBUG_MEM_USE_DOH
//#define DOH_DEBUG_MEM_USE_DOH
//#undef DOH_DEBUG_MEM_PREFER_CRT
//#define DOH_DEBUG_MEM_PREFER_CRT
//#undef DOH_DEBUG_MEM_PREFER_DOH
//#define DOH_DEBUG_MEM_PREFER_DOH

#undef DOH_DEBUG_MEM_TRACK_START
#define DOH_DEBUG_MEM_TRACK_START
#undef DOH_DEBUG_MEM_TRACK_END
#define DOH_DEBUG_MEM_TRACK_END
#undef DOH_DEBUG_MEM_DUMP_TRACK
#define DOH_DEBUG_MEM_DUMP_TRACK
#undef DOH_DEBUG_MEM_DUMP_LEAKS
#define DOH_DEBUG_MEM_DUMP_LEAKS

#undef DOH_DEBUG_DEFINES_EMPTY
#define DOH_DEBUG_DEFINES_EMPTY

